spring.application.name=security

#mongo
spring.mongodb.uri=mongodb+srv://pekka:1234@freelancer.jjye0j5.mongodb.net/?retryWrites=true&w=majority&appName=freelancer
spring.mongodb.database=security

#jwt
app.jwt.access-secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.refresh-secret=5A7134743777217A25432A462D4A614E645267556B58703273357638792F423F
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

# Cookie settings
app.cookie.secure=true
app.cookie.same-site=Strict

#CORS - production domain
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

#Brute force lock settings
app.security.max-failed-attempts=5
app.security.lock-duration-minutes=15

#production
logging.level.org.springframework.security=WARN
logging.level.com.spring.security=INFO

#5 - Swagger default off
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}

#mail
app.security.require-email-verification=false
# SMTP mail settings
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=${MAIL_FROM:no-reply@travelbooking.com}
app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}